### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [sharelatex/web-sharelatex#282]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like web-sharelatex, deleted the software history during the transition to open-source.

sharelatex https://github.com/sharelatex/web-sharelatex/commit/c06610cd729a3076ea37d9be07c54efecc802e66pen source

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask web-sharelatex developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by jpallen** [comment]
1. Since we hadn't done the original development with open source in mind, we'd ended up with some pollution of the commit logs with inclusion of private keys, etc. Since git doesn't let you alter history easily, and rather than do a full audit of all commits, it was easier just to start again with a fresh open source commit log.
2. No major problems I'm aware. Occasionally a git blame just leads back to the original open source commit, rather than the true commit/author of the change, which can make it difficult to track down where the code came from.
3. None that I'm aware of.
4. None that I'm aware of.

**Comment by gustavopinto** [comment]
Hi @jpallen,

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
