### ISSUE TITLE
Arrow keys do not work in iOS Safari for iPad

### ISSUE THREAD

**Issue by vtsatskin** [sharelatex/web-sharelatex#312]
When attempting to use the document editor on an iPad and a physical keyboard, the arrow keys do not do anything. This makes it impossible to move the cursor without tapping on the screen. In addition, selecting text with `shift+<arrow key>` is not possible so selecting large blocks of text and operating on them is not possible (e.g. Copy, cut, delete).

IOS Version: 9.3.5

**Comment by sophielee1** [comment]
In addition to the issues mentioned, pushing the arrow keys a few times disables typing afterwards.

**Comment by henryoswald** [comment]
going to close and keep issue to https://github.com/sharelatex/web-sharelatex/issues/13

**Comment by jrk** [comment]
#13 is now closed but this issue remains a huge problem in practice

**Comment by gvita** [comment]
Landed here after having this issue on iPad Pro. 
I was pushing my collaborators to sharelatex so that when traveling for conferences we could bring just our iPad Pro's with external keyboard and collaborating on LaTeX projects without having to bring our laptops. However, with this bug, sharelatex is useless for us.

**Comment by zteitler** [comment]
In September 2018 this is still a problem. As a workaround, arrow keys seem to work in rich text. (But I would *much* rather edit source!)
