### ISSUE TITLE
Out of sync + full refresh

### ISSUE THREAD

**Issue by rocarvaj** [sharelatex/web-sharelatex#348]
Hello,
Lately I've been experiencing the following. I working on a project and suddenly I get the following message:

> Sorry, this file has gone out of sync and we need to do a full refresh. 
> Please see this help guide for more information

This is OK, but the problem is that the project is then replaced with a version of a few seconds ago (therefore losing a few seconds of work). I would assume that a more reasonable behavior would be to update the remote version of the project with my current local version.

I'm using ShareLaTeX in Chrome 53.0.2785.143 m in Windows 10.

Thanks in advance for any help and I hope this report helps to improve the project.

**Comment by henryoswald** [comment]
Thanks for the report, this happens when the internet conneciton is a bit flakey between the user and our servers

**Comment by scorpionhiccup** [comment]
I'm still facing this issue,very frequently. I have tried to move closer to the wifi router... Is there anything else I can do?

**Comment by scorpionhiccup** [comment]
I'm still facing this issue,very frequently. I have tried to move closer to the wifi router... Is there anything else I can do?

**Comment by fkong7** [comment]
I'm facing this issue as well, happening every coupe of minutes when the internet connection is slow. Each time it will do a full refresh and then revert back to a previous saved version instead of updating the server with my local version. Sometimes will place my newly entered text at wrong places, usually near the end of file, causing syntax error. Is it not possible to update the server version with my local one so it's usability won't depend so much on internet quality?

**Comment by ShaneKilkelly** [comment]
Just to clarify, is this happening on www.overleaf.com, or on a local Community Edition installation?

**Comment by fkong7** [comment]
@ShaneKilkelly This is happening on www.overleaf.com.
