### ISSUE TITLE
Ctrl+L conflicts with browser hotkey

### ISSUE THREAD

**Issue by jamy015** [sharelatex/web-sharelatex#440]
The Ctrl+L 'Go To Line' hotkey conflicts with the Ctrl+L 'Focus on Location Bar' hotkey in most browsers.

In Firefox, this means that the 'enter line number' box still pops up when I press Ctrl+L, but the focus goes to the location bar, and I need to press Tab thrice to get back to the box. This makes the hotkey a lot less useful, because it doesn't save me any time over grabbing the mouse.

It would probably be useful to make sure none of the hotkeys conflict with common browser hotkeys.

**Comment by Monadologie** [comment]
To my mind, the best way we can handle that is by changing CTRL+L hotkey used by the website.
However, you can still change your browser CTRL+L hotkey. But this seems very boring for users. 
That's why I suggest to change the hotkey used by the website; or if it's possible to let the user choose his own hotkeys by creating a new "system" to handle that ... More precisely, user could choose his own hotkeys with the same actual box that appears. These hotkeys could be saved with sessions or into the database, it's up to us.
What do you think @jpallen @jamy015?
I will take a more precise look at these options *shrotly*.

**Comment by jamy015** [comment]
I looked into this a bit more and it seems that it's actually possible to prevent the default behaviour from happening using `preventDefault()` and `stopPropagation()` (see [this comment on StackOverflow](https://stackoverflow.com/questions/3680919/overriding-browsers-keyboard-shortcuts#comment31717798_3680984)). This way, we could keep the shortcuts as they are (because there's a good case to be made for Ctrl+L: it's the 'go to line' shortcut in lots of text editors, and users may already be used to it).

Regardless of this, I think letting users change their hotkeys is a great idea; that way, anyone who doesn't like the defaults can just set something else.

**Comment by jamy015** [comment]
It seems that either ShareLaTeX or a Firefox update has changed something, as I now cannot reproduce this either on Firefox 52 or Internet Explorer 11.

Feel free to re-open the issue if the problem does crop up with some other browser.
